const express = require('express');
const router = express.Router();
const userscontroller = require('../app/controllers/UsersController');
router.post('/order',userscontroller.order);
router.post('/cancelorder',userscontroller.cancelorder);
router.get('/myorders',userscontroller.myorders);
router.get('/myorderswaitconfirm',userscontroller.myordersstatus1);
router.get('/myordersfinished',userscontroller.myordersstatus2);
router.post('/changeaddress',userscontroller.changeaddress);
router.post('/changepassword',userscontroller.changepassword);
router.get('/private',userscontroller.testtoken,userscontroller.privateUser);
router.get('/Login',userscontroller.login);
router.get('/information',userscontroller.information);
router.get('/password',userscontroller.password);
router.get('/Logout',userscontroller.logout);
router.get('/Register',userscontroller.register);
router.post('/checkusername',userscontroller.checkusername);
router.post('/checkinformation',userscontroller.checkinformation);
router.post('/checkpassword',userscontroller.checkpassword);
router.post('/createaccount',userscontroller.createaccount);
router.post('/authentication',userscontroller.authentication);
module.exports = router;